logging:
  level:
    liquibase: INFO

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_DATABASE:economics}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
server:
  port: ${PORT:8001}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  healthcheck:
    enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 30
    preferIpAddress: true