INSERT INTO WAREHOUSES (UUID, NAME, LATITUDE, LONGITUDE) VALUES (UUID(), 'Warehouse 1', 100, 200);
INSERT INTO WAREHOUSES (UUID, "NAME", LATITUDE, LONGITUDE) VALUES (UUID(), 'Warehouse 2', 110, 90);
INSERT INTO WAREHOUSES (UUID, "NAME", LATITUDE, LONGITUDE) VALUES (UUID(), 'Warehouse 3', 120, 100);
INSERT INTO WAREHOUSES (UUID, "NAME", LATITUDE, LONGITUDE) VALUES (UUID(), 'Warehouse 4', 50, 40);
INSERT INTO WAREHOUSES (UUID, "NAME", LATITUDE, LONGITUDE) VALUES (UUID(), 'Warehouse 5', 90, 130);
