--liquibase formatted sql

--changeset Alexander:1.0 (dbms:h2)
CREATE TABLE WAREHOUSES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    UUID BINARY(16) DEFAULT UUID() UNIQUE NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    LATITUDE DECIMAL(5, 2) NOT NULL,
    LONGITUDE DECIMAL(5, 2) NOT NULL
);