--liquibase formatted sql

--changeset Alexander:1.2 (dbms:h2)
ALTER TABLE WAREHOUSES
    ADD COLUMN CAPACITY DECIMAL(5, 0) NOT NULL DEFAULT 0
    CONSTRAINT CAPACITY_POSITIVE_CHECK CHECK (CAPACITY >= 0);

UPDATE WAREHOUSES SET CAPACITY = 200;